In [ ]:
numbers=(1,2,3,4,'moin')

In [12]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5],[9,9,9,9,9]])

print(arr)
print(type(arr))
print(arr.ndim)

[[1 2 3 4 5]
 [9 9 9 9 9]]
<class 'numpy.ndarray'>
2


In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [17]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])


print( arr[1,0])

6


In [23]:
import numpy as np

arr = np.array([   [  [1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]  ]   ])

print(arr[0,-0,0])

1


In [30]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[0:6:4])

[1 5]


In [33]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0, 1:3])

[2 3]


In [ ]:
import copy

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)


x=arr

[42  2  3  4  5]
[1 2 3 4 5]


In [39]:
import numpy as np

arr1 = np.array([10, 20, 30])
arr2 = arr1.view()   
arr1[0]=99


print(arr1)  
print(arr2)



[99 20 30]
[99 20 30]
