In [ ]:
numbers=(1,2,3,4,'moin')

In [12]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5],[9,9,9,9,9]])

print(arr)
print(type(arr))
print(arr.ndim)

[[1 2 3 4 5]
 [9 9 9 9 9]]
<class 'numpy.ndarray'>
2


In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [17]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])


print( arr[1,0])

6


In [23]:
import numpy as np

arr = np.array([   [  [1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]  ]   ])

print(arr[0,-0,0])

1


In [30]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[0:6:4])

[1 5]


In [33]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0, 1:3])

[2 3]


In [ ]:
import copy

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)


x=arr

[42  2  3  4  5]
[1 2 3 4 5]


In [39]:
import numpy as np

arr1 = np.array([10, 20, 30])
arr2 = arr1.view()   
arr1[0]=99


print(arr1)  
print(arr2)



[99 20 30]
[99 20 30]


In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(6, 2)

print(newarr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# [[1,2],[3,4],[5,6]][[7,8],[9,10],[11,12]]

#[ [[1,2],[3,4]] [[5,6],[7,8],] [[9,10],[11,12]  ]  ]



[[1],
 [2],
 [3],
 [4],
 [5],
 [6]
]
[1,2,3,4,5,6]

newarr = arr.reshape(2, 6, 1)

print(newarr)

[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]
  [10]
  [11]
  [12]]]


In [11]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [12]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 5)

print(x)

(array([4]),)


In [20]:
import numpy as np

arr = np.array([0,1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([0, 2, 4, 6, 8]),)


In [24]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 100)

print(x)

4
